services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src
      - ./index.js:/app/index.js
      - .env:/app/.env
      - ./uploads:/app/uploads
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:5
    container_name: cadt-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cadt-redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
volumes:
  mongodbdata:
